name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次（UTC时间0点）

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v3
        with:
          ref: main  # 替换为你的分支名

      - name: Add upstream
        run: git remote add upstream https://github.com/wenye01/Chrono.git

      - name: Fetch and merge upstream
        run: |
          git fetch upstream
          git merge upstream/main  # 替换为原始仓库的默认分支名

      - name: Push changes
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin main  # 替换为你的分支名
